### ISSUE TITLE
Refactor Tripletexjs

### ISSUE THREAD

**Issue by cobraz** [bjerkio/tripletexjs#14]
Tripletexjs was created 4 years ago, based on Swagger Codegen. 

A while ago it stopped building due to some package updates, and the templates this project is based on does not benefit the growth of it. It's time to reproduce.

I've had success with a new revision of a ~~Swagger~~ OpenAPI Codegen client with [CloudIQ's API](https://github.com/bjerkio/crayon-api-js). I think we should reuse most of that – it's a more elegant solution. `request` has officially been marked as depreciated (request/request#3141), so I want to find a solution that uses something else.

**Comment by cobraz** [comment]
I've done some testing on reproducing this package. First I noticed that [Tripletex's Swagger file](https://tripletex.no/v2/swagger.json) is not actually according to [specification](https://online.swagger.io/validator/debug?url=https%3A%2F%2Ftripletex.no%2Fv2%2Fswagger.json) . Probably why it stopped building. This fact led me to try to build a [transforming utility](https://github.com/bjerkio/tripletexjs/pull/15/files#diff-63238f3907d5bcf0c8a4be004d7d62ea) (thinking it only was duplicated / missing `operationId`) – no dice. There are still stuff to uncover, the OpenAPI Generator is failing due to memory issues caused by something in the Swagger files or it could be array type, maybe unused definitions.

OpenAPITools/openapi-generator#2503, OpenAPITools/openapi-generator#4398 or OpenAPITools/openapi-generator#5201 could be relevant.

I have added a [comment](https://trello.com/c/pFuV7VDq/62-integrasjoner-api-%F0%9F%94%8C#comment-5e7930418ebbd31bce5e874b) on their Trello board to see if they will try and fix it. It looks to me that the Swagger file is automatically updated.

*PS: I will continue with trying to fix problems with Swagger if we don't get response on our [comment](https://trello.com/c/pFuV7VDq/62-integrasjoner-api-%F0%9F%94%8C#comment-5e7930418ebbd31bce5e874b). In the event where we need to transform the Swagger file, I will be adding that to a separate repository to keep it away from this client.*

Meanwhile, we can follow the current status with this nice badge:
![](https://online.swagger.io/validator?url=https%3A%2F%2Ftripletex.no%2Fv2%2Fswagger.json)
👆That will update if they fix it!

**Comment by zsoltherpai** [comment]
There is a work in progress version of the tripletex swagger spec that fixes the validation issues (non-unique operation ids).

You check if it works better with your tools:
https://triplepub.s3-eu-west-1.amazonaws.com/swagger.json

Note that the operation ids are still subject to change, they will be finalized shortly.

**Comment by cobraz** [comment]
Hello, @zsoltherpai!

Thank you so much for that – it helps a lot! I have also cleaned up a lot of the file, fixing all validation issues. It seems to me that it still has some problems with generation. I even generated a [YAML-file](https://gist.githubusercontent.com/cobraz/e46754a820e837862afa70e0851f7b00/raw/438b82b13c3c724b106f84ba375a89a612df532a/tripletex-swagger.yaml) with those validation fixed. However, still getting an out of memory issue (even with >12gb memory). I'm going to open an issue at OpenAPITools to see if they can help with that.

Again, thanks for the interest in this!

**Comment by cobraz** [comment]
I've escalated this issue to OpenAPI Generator:
OpenAPITools/openapi-generator#6597

Hope to get some help from them :)

**Comment by zsoltherpai** [comment]
The swagger spec of tripletex has unique operation ids now:
https://validator.swagger.io/validator/debug?url=https://tripletex.no/v2/swagger.json

**Comment by cobraz** [comment]
Great, thanks! We'll update this and bjerkio/go-tripletex as well 👍

**Comment by cobraz** [comment]
We have released v3 of Tripletexjs now, so I'm closing this! At last 😅
