### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kasperaamodt** [bjerkio/tripletexjs#69]
Hello,

I'm trying to use this package, but I can't get it to work. I have the following file, but it does not work. Am I doing something wrong? I'm using it with SSR in Next.js, on the server side.

```
// src/server/tripletex/client.ts
import { env } from '@env/server.mjs';
import { TripletexClient } from 'tripletexjs';

declare global {
    // eslint-disable-next-line no-var
    var tt: TripletexClient | undefined;
}

export const tt =
    global.tt ||
    new TripletexClient({
        baseUrl: 'https://api.tripletex.io',
        employeeToken: env.TRIPLETEX_EMPLOYEE_TOKEN,
        consumerToken: env.TRIPLETEX_CONSUMER_TOKEN,
        expirationDate: new Date('2023-02-25'),
    });

if (env.NODE_ENV !== 'production') {
    global.tt = tt;
}
```

**Comment by cobraz** [comment]
I have never used `tripletexjs` with SSR or any other front-end tool. I don't know what is causing any issues however.

Can you share what you're expecting it to do? This file in it self should only construct a client class, there shouldn't be much more.

**Comment by kasperaamodt** [comment]
I'm importing this class and calling stuff with it, like `const customers = await tt.customer().list()`. But it always returns undefined.

**Comment by cobraz** [comment]
I don't understand why you're using `global` here, does removing all that make a difference?

**Comment by kasperaamodt** [comment]
No, I have also tried using this directly, and it still does not work.

**Comment by kasperaamodt** [comment]
@cobraz turns out I'm just stupid. It works, with SSR and everything. Does v3 have any documentation?

**Comment by cobraz** [comment]
I don't think we've documented the methods, but only the general idea of the API.

Would love to get some help on that, also feedback on how it feels working with it!

**Comment by kasperaamodt** [comment]
I will definitely let you know any feedback I have after working with it!

Can you do CRUD with this lib, or just read?
